### ISSUE TITLE
gettext.app.src is not rebar-friendly

### ISSUE THREAD

**Issue by amarandon** [etnt/gettext#1]
Adding gettext as a rebar dependency fails with this error:

      ERROR: Failed to extract name from 
      /home/al/projects/matome/deps/gettext/src/gettext.app.src: 
      {25, erl_parse,  ["syntax error before: ",  "'.'"]}

gettext.app.src is not a valid erlang config file (it's intended to be processed by Perl in gettext's build). A quick workaround:

      cp ebin/gettext.app src/gettext.app.src

**Comment by lemenkov** [comment]
Fixed in 15603623de54d4b38962d7702ac7c78bafb79b95, 2cd2fe88906cdadb035c1dbba8830176cacd14d7.

@etnt I believe you can close this ticket now as "RESOLVED".

**Comment by richcarl** [comment]
Closing.
